# .github/workflows/cd.yml

name: Continuous Deployment

on:
  push:
    branches: ["master"]
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPO }}

      - uses: actions/checkout@v3
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop ${{ secrets.DOCKERHUB_REPO }}
            docker pull ${{ secrets.DOCKERHUB_REPO }}
            docker run -d -p 80:80 ${{ steps.meta.outputs.tags }}

  telegram:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notification on Deploy
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Recent Deploy by ${{ github.actor }} with ${{ github.repository }}
            Preview : http://${{ secrets.SSH_HOST }}
