# .github/workflows/telegram.yml

name: CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPO }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ steps.meta.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

  telegram:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Notification on Push
        if: github.event_name == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Recent Push by ${{ github.actor }} on ${{ github.repository }}.
            Message: ${{ github.event.head_commit.message }}
            Link: ${{ github.event.head_commit.url }}

      - name: Notification on PR
        if: github.event_name == 'pull_request'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Recent PR by ${{ github.actor }} from ${{ github.head_ref }} to ${{ github.base_ref }}
            PR Title : ${{ github.event.pull_request.title }}
            PR link: ${{ github.event.pull_request.html_url }}
            Please review @${{ secrets.OWNER }}
