# .github/workflows/logs.yml

name: Logs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPO }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  telegram:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Notification Log
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_LOGS }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          message: |
            Recent ${{ github.event_name }} on branch ${{ github.ref }}

            Commit author: ${{ github.event.head_commit.author.name }}

            Commit message: ${{ github.event.head_commit.message }}

            Commit URL: ${{ github.event.head_commit.url }}
