# .github/workflows/logs.yml

name: Logs

on:
  push:
    branches: ["*"]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Notification Log
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_LOGS }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Recent ${{ github.event_name }} on ${{ github.repository }} by ${{ github.actor }}:
            Commit link: ${{ github.event.head_commit.url }}
            Commit message: ${{ github.event.head_commit.message }}
            Commit author: ${{ github.event.head_commit.author.name }}
