# .github/workflows/telegram.yml

name: Notify Owner

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Notification on Push
        if: github.event_name == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Recent Push by ${{ github.actor }} on ${{ github.repository }}.
            Message: ${{ github.event.head_commit.message }}
            Link: ${{ github.event.head_commit.url }}

      - name: Notification on PR
        if: github.event_name == 'pull_request'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Recent PR by ${{ github.actor }} from ${{ github.head_ref }} to ${{ github.base_ref }}
            PR Title : ${{ github.event.pull_request.title }}
            PR link: ${{ github.event.pull_request.html_url }}
            Commit link: ${{ github.event.pull_request.head.sha }}
            Reviewers: @${{ github.event.pull_request.requested_reviewers }}
