# .github/workflows/telegram.yml

name: Telegram Notification Kok Gak Bisa

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Recent activity \n
            ${{ github.event_name }} ${{ github.ref }} by @${{ github.actor }} \n
            ${{ github.event.push.html_url }}
            ${{ github.event.head_commit.message }}
